### ISSUE TITLE
Need your model to complete comparison

### ISSUE THREAD

**Issue by nbbllxx0** [Owen718/Perceiving-and-Modeling-Density-is-All-You-Need-for-Image-Dehazing#2]
I would like to compare your model with my VIT in my conference paper, I wonder when the model could be released?

**Comment by Owen718** [comment]
Hi！ We already release the testing code in the _Inference_Code_.

**Comment by nbbllxx0** [comment]
Thanks for the reply, the test.py seems unable to read .png or.rgb files, though the _test_list_ can be recognized and printed correctly.


G:\anaconda3\envs\pytorch\python.exe G:/ECCV22-Perceiving-and-Modeling-Density-for-Image-Dehazing-main/Inference_Code/test.py --pk_path PMNET_Haze4k.tjm --save_path dehaze --test_path hazy
['1.png', '2.png', '3.png', '4.png', '5.png']
Traceback (most recent call last):
  File "G:\ECCV22-Perceiving-and-Modeling-Density-for-Image-Dehazing-main\Inference_Code\test.py", line 42, in <module>
    Net=torch.jit.load(opt.pk_path,map_location=torch.device('cuda:0')).eval().cuda()
  File "G:\anaconda3\envs\pytorch\lib\site-packages\torch\jit\_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: 
Unknown type name 'NoneType':
Serialized   File "code/__torch__/model/TSANet16.py", line 156
  def forward(self: __torch__.model.TSANet16.MixScale,
    argument_1: Tensor,
    argument_2: Tensor) -> NoneType:
                           ~~~~~~~~ <--- HERE
    _53 = self.factor
    _54 = (self.mixblock).forward(_53, )


Process finished with exit code 1

**Comment by Owen718** [comment]
Okay~

**Comment by zhenyuan1234** [comment]
Did you successfully test the code
?
