### ISSUE TITLE
Can I ask for more accurate SSIM in Table 3?

### ISSUE THREAD

**Issue by cecret3350** [Owen718/Perceiving-and-Modeling-Density-is-All-You-Need-for-Image-Dehazing#5]
Hi @Owen718 , thanks for your amazing work, and congratulations!

Recently I am also working on image dehazing and I would like to cite your paper and compare with it. But one problem is that the SSIM you reported in table 3 is only accurate to two decimal places，such as 0.99 and 0.98. The error introduced by rounding seems to be huge for SSIM. For a fairer and more accurate comparison, can I know your more precise experimental results, especially SSIM?

Looking forward to your reply!

**Comment by Owen718** [comment]
Hi！ I think you can re-trained our method for a fair and convinced comparison! I have not retained SSIM results of higher precision.  Sorry for that.

**Comment by cecret3350** [comment]
Thank you for replying! Looking forward to your complete code!

**Comment by cecret3350** [comment]
> Hi！ I think you can re-trained our method for a fair and convinced comparison! I have not retained SSIM results of higher precision. Sorry for that.


Thank you for replying! Looking forward to your complete code!

**Comment by Owen718** [comment]
Maybe we can have some interesting collaboration about image dehazing. Email to me if you interested or have some doubt.

**Comment by cecret3350** [comment]
> Maybe we can have some interesting collaboration about image dehazing. Email to me if you interested or have some doubt.

Appreciate it! I‘ll send you an email in the near future.

**Comment by cecret3350** [comment]
> Maybe we can have some interesting collaboration about image dehazing. Email to me if you interested or have some doubt.

Sorry for bothering you again @Owen718 . I've sent you an email several days ago, I was wondering wether I sent it to the right  email address (I sent it to maserowen718@gmail.com).

**Comment by Owen718** [comment]
Hi! I cannot find your email with this address. Can you tell me the email address you used?  Or may be you can send an email to this address again (201921114031@jmu.edu.cn) ?

**Comment by cecret3350** [comment]
> Hi! I cannot find your email with this address. Can you tell me the email address you used? Or may be you can send an email to this address again ([201921114031@jmu.edu.cn](mailto:201921114031@jmu.edu.cn)) ?

Thank you for your reply, I have resent the email to the new address.

**Comment by Owen718** [comment]
Solved.
