### ISSUE TITLE
Google Drive Link fopr checkpoints and data

### ISSUE THREAD

**Issue by PratikGarai** [Owen718/Perceiving-and-Modeling-Density-is-All-You-Need-for-Image-Dehazing#6]
Hi, 
Is there any way I can get the google drive link of the pre-trained weights?

Thanks in advance

**Comment by Owen718** [comment]
I apologize for the delayed response. I have updated the readme document and the Google Drive download link. Please feel free to contact me if you have any further questions or concerns.
[https://drive.google.com/file/d/1RxOxgCf2aAlRLPbUhHHlUyAQ2c3Se2ZK/view?usp=sharing](https://drive.google.com/file/d/1RxOxgCf2aAlRLPbUhHHlUyAQ2c3Se2ZK/view?usp=sharing)
