### ISSUE TITLE
test code

### ISSUE THREAD

**Issue by zhenyuan1234** [Owen718/Perceiving-and-Modeling-Density-is-All-You-Need-for-Image-Dehazing#8]
Hello, the test code is not complete, can you release the complete code?

**Comment by Owen718** [comment]
Hi
The test code is complete.
Could you please describe the problem you meet ?

**Comment by zhenyuan1234** [comment]
I had an error like this when I was testing, thanks:
File "G:\ECCV22-Perceiving-and-Modeling-Density-for-Image-Dehazing-main\Inference_Code\test.py", line 42, in
Net=torch.jit.load(opt.pk_path,map_location=torch.device('cuda:0')).eval().cuda()
File "G:\anaconda3\envs\pytorch\lib\site-packages\torch\jit_serialization.py", line 161, in load
cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError:
Unknown type name 'NoneType':
Serialized File "code/torch/model/TSANet16.py", line 156
def forward(self: torch.model.TSANet16.MixScale,
argument_1: Tensor,
argument_2: Tensor) -> NoneType:
~~~~~~~~ <--- HERE
_53 = self.factor
_54 = (self.mixblock).forward(_53, )

**Comment by zhenyuan1234** [comment]
Can you tell me where the .py file for the model

**Comment by Owen718** [comment]
The TJM-based inference don't need any python file of model. 
Please refer to the readme.md .

**Comment by Owen718** [comment]
Please confirm that the tjm model has been **loaded** successfully and **image path is correct.**
